# Generated by Django 3.1.3 on 2020-11-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developments_Test', '0002_remove_users_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='full_name',
        ),
    ]
